### ISSUE TITLE
Dont see buildpack picking local bindings

### ISSUE THREAD

**Issue by doddisam** [dmikusa/binding-tool#146]
Hello,

I am trying to use local binding for bellsoft-liberica and i have created the mapping using ( bt dm -b paketo-buildpacks/bellsoft-liberica). When i try to run pack build i always see it still goes to internet. Expectation is to using the binding and fetch from local. Can someone help here?

pack build demo --buildpack=harbor.dell.com/pcf-images/paketobuildpacks/java:latest   --builder=harbor.dell.com/pcf-images/korifi/kob/kpack-kob@sha256:6d8165c59b7e01b23de2f32203601e84931e9d5f2029dae2fbe43f3c13a3625f --path cf-sample-sb-0.0.1-SNAPSHOT.jar --volume /var/java/bindings:/bindings --env SERVICE_BINDING_ROOT=/bindings

Below are the outputs.

![image](https://github.com/dmikusa/binding-tool/assets/89137330/d32b62a8-0950-41f5-b6df-0bd0d97a3951)

![image](https://github.com/dmikusa/binding-tool/assets/89137330/b8f6325a-1913-4dc7-99d5-6e3d4e1a63b4)

![image](https://github.com/dmikusa/binding-tool/assets/89137330/3f3a22b5-fc14-439a-ad87-fd05f291c921)

**Comment by doddisam** [comment]
I got this working by clearing docker cache.

**Comment by dmikusa** [comment]
Sorry for the slow response, glad you got that resolved & thanks for posting your fix.
