### ISSUE TITLE
Documentation: Update README with installation instructions

### ISSUE THREAD

**Issue by kiranpatel11** [dmikusa/binding-tool#2]
README has usage instructions but the installation instructions are not clear.

**Comment by dmikusa-pivotal** [comment]
Sure thing. Do you mean specific instructions to install the binary?

At the moment, that would be:

1. Download the binary from the releases page.
2. Mark it executable (Linux/Mac)
3. Move it to your PATH

If that sounds clear I can add a slightly more verbose version of that to the README.

**Comment by kiranpatel11** [comment]
I assume the binary has to be renamed to `bt` as well.
