### ISSUE TITLE
Error while generating bindings for bellsoft-liberia jdk

### ISSUE THREAD

**Issue by kiranpatel11** [dmikusa/binding-tool#3]
Command : `bt dependency-mapping -b paketo-buildpacks/bellsoft-liberica`
Env: WSL2 ubuntu 20.04.03 LTS

Error: 
```
thread '<unnamed>' panicked at 'Download of https://download.bell-sw.com/vm/22.1.0/bellsoft-liberica-vm-core-openjdk17.0.3+7-22.1.0+1-linux-amd64.tar.gz failed with error copy failed', src/deps.rs:109:33
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'unable to get lock: PoisonError { .. }', src/deps.rs:106:45
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::result::unwrap_failed
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1613:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'unable to get lock: PoisonError { .. }', src/deps.rs:106:45
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::result::unwrap_failed
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1613:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by dmikusa-pivotal** [comment]
I have had this happen once or twice. It has been intermittent though and re-running the command has resolved the issue for me. 

The `with error copy failed` happens when reading from the response from the server, so it could be networking related to an issue with downloading that particular file. I know that the file referenced in your failure message is the largest file in one of the paketo buildpacks, weighing in around 500M.

At any rate:

1. Try again a few times
2. Try downloading with curl or your browser, make sure that works & see what kind of download speeds you're getting
3. I'll keep this open as I can try to improve the error messages being generated here, perhaps get something more meaningful to show up.

**Comment by jansu76** [comment]
I have a similar issue, it sort of looks like something is timing out when downloading a big binary

```
bt dependency-mapping -b paketo-buildpacks/bellsoft-liberica
thread '<unnamed>' panicked at 'Download of https://github.com/bell-sw/Liberica/releases/download/19.0.1+11/bellsoft-jdk19.0.1+11-linux-amd64.tar.gz failed with error copy failed', src/deps.rs:123:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'unable to get lock: PoisonError { .. }', src/deps.rs:120:45
thread '<unnamed>' panicked at 'unable to get lock: PoisonError { .. }', src/deps.rs:120:45
Error: thread 'thread panic: Download of https://github.com/bell-sw/Liberica/releases/download/19.0.1+11/bellsoft-jdk19.0.1+11-linux-amd64.tar.gz failed with error copy failed<unnamed>
' panicked at 'unable to get lock: PoisonError { .. }', src/deps.rs:120:45
```
bt manages to download about 170M of the 205M file before error

`-rw-rw-r-- 1 user user 170926080 tammi   5 14:09 bellsoft-jdk19.0.1+11-linux-amd64.tar.gz
`

If I download the file with curl, it works fine

```
curl -L https://github.com/bell-sw/Liberica/releases/download/19.0.1+11/bellsoft-jdk19.0.1+11-linux-amd64.tar.gz --output testfile
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  205M  100  205M    0     0  5804k      0  0:00:36  0:00:36 --:--:-- 5973k
```

**Comment by dmikusa** [comment]
@jansu76 is this consistently happening for you? You can try adjusting `BT_CONN_TIMEOUT` and `BT_REQ_TIMEOUT`. 

These are environment variables that the app will read and use to adjust the client's [TCP connection timeout](https://docs.rs/ureq/2.6.1/ureq/struct.AgentBuilder.html#method.timeout_connect) and [request timeout](https://docs.rs/ureq/2.6.1/ureq/struct.AgentBuilder.html#method.timeout). I suspect it is the latter that's causing issues. 

Please try a large value there and see if that helps. If so, I can adjust the client settings (probably should set `timeout_read` and `timeout_write` instead).

**Comment by jansu76** [comment]
Thanks, I will try that and report findings, was not aware of those timeout variables.

**Comment by jansu76** [comment]
Setting `BT_REQ_TIMEOUT` fixed the issue, super!

**Comment by dmikusa** [comment]
Thanks for the feedback. That's my fault I should have documented those :) I'll get that fixed too.
