### ISSUE TITLE
can't download local file 

### ISSUE THREAD

**Issue by GeTOUO** [dmikusa/binding-tool#75]
my project has bindings in maven pom.xml:

```
                <binding>
		        ${project.basedir}/bindings:/platform/bindings
		</binding>
```

run: `mvn spring-boot:build-image -Pnative`

**but error:**  

[INFO]     [creator]     Paketo Buildpack for Syft 1.32.1
[INFO]     [creator]       https://github.com/paketo-buildpacks/syft
[INFO]     [creator]         Downloading from file:///bindings/dependency-mapping/binaries/syft_0.84.0_linux_amd64.tar.gz
[INFO]     [creator]     unable to invoke layer creator
[INFO]     [creator]     unable to get dependency syft
[INFO]     [creator]     unable to download file:///bindings/dependency-mapping/binaries/syft_0.84.0_linux_amd64.tar.gz
[INFO]     [creator]     unable to open source file /bindings/dependency-mapping/binaries/syft_0.84.0_linux_amd64.tar.gz
[INFO]     [creator]     open /bindings/dependency-mapping/binaries/syft_0.84.0_linux_amd64.tar.gz: no such file or directory
[INFO]     [creator]     ERROR: failed to build: exit status 1

**Comment by dmikusa** [comment]
That looks correct, but I don't know what's in your `${project.basedir}/bindings` directory. There's an example of how to configure this here: https://github.com/dmikusa/binding-tool/issues/8#issuecomment-1548040247

Please try comparing what you have to that example and let if you're still stuck.

**Comment by GeTOUO** [comment]
@dmikusa 太棒了，非常感谢您！我已经在我本地成功执行了。

```
[INFO]     [creator]     Paketo Buildpack for Syft 1.32.1
[INFO]     [creator]       https://github.com/paketo-buildpacks/syft
[INFO]     [creator]         Downloading from file:///platform/bindings/dependency-mapping/binaries/syft_0.84.0_linux_amd64.tar.gz
[INFO]     [creator]         Verifying checksum
[INFO]     [creator]         Writing env.build/SYFT_CHECK_FOR_APP_UPDATE.default
```

接下来我要解决更棘手的问题了，我们的线上ci流程中，Jenkins运行在docker中。我似乎没有办法让这个 binging生效。目前一点头绪都没有！
